### PR TITLE
Update to recent version 3.9.1

### PR DESCRIPTION
**Pull request by idhamari**
Please do not merge until all updates are complete. I added the PR to get early feedback!

So far: Chapters 1,2,3 and 4 are updated. 

Notes and suggestions for the next commits:

1. [x] some images are not used (they will be removed).
2. [x] to make it easier to track images, indices will be added to the file name e.g. p0302_04_titles.png which means chapter3, page 2 figure 4 
3. [x] to keep the aspect ratio and avoid wrong zooming, either height or width will be used. Note: ARX use simple browser so height and width must be specified correctly. 
4. [x] all image filenames are updated to reflect the chapter, section and order in the webpage. Image files are now organised inside relative chapters, the non-used images are deleted. 
5. [x] some images are updated to include the location of the figure in red boxes.  
6. [x] Links are using relative path (not sure if this may affect ARX website) 
7. [x] add links to the pages in the readme file to explain where is each page in the help contents
8. [x] create index.html for a simple local navigation when needed   
9. [ ] cleaning: will be done after a feedback 
10. [ ] update ARX PR to include a template to mention if update help is needed.

Others: 

- For automating, I suggest using the pages feature in GitHub and using the GitHub website instead of ARX website (the link should be changed as well in ARX code).  Here is an example from my fork (still not completed): https://iabih.github.io/arx-help/
- Reorganize the files into chapters and indices to the file name. Add a prospectives folder to keep prospective files.
- Add more figures, explanations, and, examples (for example creating a hierarchy is not clear). 
- Using GitHub tags instead of keeping folders of old versions.
- The img_raw folder is not needed (one has to create and edit new images when the interface changes).

### CODE REVIEW

**Comment by prasser** [comment]
Quick feedback:
- URLs in readme point to iaBIH repos.
- Please don't add section numbers the files are used in other places (e.g. the website) as well, where the numbering is different / not used.
- If you replace images, please use images with the same width and height.

**Comment by prasser** [comment]
Re other points:

1. To keep track, I suggest changing the help files when needed as soon as a new related PR is merged into ARX (or at least create an issue here).

Of course this would be the ideal solution.

2. For automating, I suggest using the pages feature in GitHub and using the GitHub website instead of ARX website (the link should be changed as well in ARX code). Here is an example from my fork (still not completed): https://iabih.github.io/arx-help/ 

Please not. Never change a running system and the help runs very well. 

3. Reorganize the files into chapters and indices to the file name. Add a prospectives folder to keep prospective files.

Please not. Never change a running system and the help runs very well. 

4. Add more figures, explanations, and, examples (for example creating a hierarchy is not clear).

Sure. Good idea.

5. Using GitHub tags instead of keeping folders of old versions.

I believe we should leave it as is. People might run older versions of ARX and with this design we can also easily update the help for those old installations. Also "deploying" is straight-forward with this structure (just copy whole repo to webspace).

6. The img_raw folder is not needed (one has to create and edit new images when the interface changes).

Maybe.

**Comment by idhamari** [comment]
Thanks for your quick feedback


>  URLs in readme point to iaBIH repos.

updated to ARX server

>Please don't add section numbers the files are used in other places (e.g. the website) as well, where the numbering is different / not used.

I don't understand, could you please explain more?

>    If you replace images, please use images with the same width and height.

The original images sometimes are very small and not readable. We can control how to view the images by changing the width (I can test how they look in different screen sizes). Resizing the images may stretch them.

>    For automating, I suggest using the pages feature in GitHub and using the GitHub website instead of ARX website (the link should be changed as well in ARX code). Here is an example from my fork (still not completed): https://iabih.github.io/arx-help/
>Please not. Never change a running system and the help runs very well.

We are changing a running system with another improved running system but it is your decision. 

> Reorganize the files into chapters and indices to the file name. Add a prospectives folder to keep prospective files.
> Please not. Never change a running system and the help runs very well.

It took me some time to find out what is the actual structure of the help and locate files and images. Using indices and chapters will make it easier for developers to modify/update files when needed in a simpler way instead of searching every time.  

> Using GitHub tags instead of keeping folders of old versions.
>I believe we should leave it as is. People might run older versions of ARX and with this design we can also easily update the help for those old installations. Also "deploying" is straight-forward with this structure (just copy whole repo to webspace).

Thanks for the explanation.  The old help files are stored in an external server so I think they will not be affected maybe we can start using tags from the next release.

**Comment by prasser** [comment]
> Thanks for your quick feedback
> 
> > URLs in readme point to iaBIH repos.
> 
> updated to ARX server

But that also doesnt make a lot of sense I think. Maybe you need to elaborate further why your created the readme? I would have expected the URLs to point to files in this repo (not the iaBIH fork and not the website),

> > Please don't add section numbers the files are used in other places (e.g. the website) as well, where the numbering is different / not used.
> 
> I don't understand, could you please explain more?

The files in the help are also used directly as parts of the website. For example, this page

https://arx.deidentifier.org/overview/privacy-criteria/

Simply contains the content of

help/v3.9.1/methods/privacy.html

If you add numbers (like 1.1. in this case) those would appear on the website...

> > If you replace images, please use images with the same width and height.
> 
> The original images sometimes are very small and not readable. We can control how to view the images by changing the width (I can test how they look in different screen sizes).

Maybe this can work. But you need to consider that they are shown in a very simplistic and limited "browser" as part of the ARX help. This "browser" does not support all features that you would usually expect from a browser.

> Resizing the images may stretch them.

Not if you carefully took the screenshots in the first place.

> > For automating, I suggest using the pages feature in GitHub and using the GitHub website instead of ARX website (the link should be changed as well in ARX code). Here is an example from my fork (still not completed): https://iabih.github.io/arx-help/
> > Please not. Never change a running system and the help runs very well.
> 
> We are changing a running system with another improved running system but it is your decision.

Currently, I'm not convinced that there are significant improvements, but I see a lot of changes. Might not make sense to change a lot for minor improvements. Why is GitHub better suited than our own webspace?

> > Reorganize the files into chapters and indices to the file name. Add a prospectives folder to keep prospective files.
> > Please not. Never change a running system and the help runs very well.
> 
> It took me some time to find out what is the actual structure of the help and locate files and images. Using indices and chapters will make it easier for developers to modify/update files when needed in a simpler way instead of searching every time.

I agree that an index like you created in the readme is a good thing to add. I don't really like the idea of renaming the files according to the chapters/sections that they are currently located in, though.

> > Using GitHub tags instead of keeping folders of old versions.
> > I believe we should leave it as is. People might run older versions of ARX and with this design we can also easily update the help for those old installations. Also "deploying" is straight-forward with this structure (just copy whole repo to webspace).
> 
> Thanks for the explanation. The old help files are stored in an external server so I think they will not be affected maybe we can start using tags from the next release.

But why? I don't see why we would benefit from tags and if we stick with the current layout, we can also easily update old versions of the help while keeping track of changes. I must admin, though, that this is a quite hypothetical scenario.

**Comment by idhamari** [comment]
Thanks for the explanation!

> But that also doesnt make a lot of sense I think. Maybe you need to elaborate further why your created the readme? I would have expected the URLs to point to files in this repo (not the iaBIH fork and not the website),

I needed (1) a simple way to find the webpage based on the ARX help. (2) a simple way to test the uploaded files e.g. how they look in the browser. 

Since this is complicated as this requires the new files to be copied to an external server. I suggest developers should (1) make a fork. (2) activate GitHub pages (3) in ARX change the link to the GitHub pages of the fork (which should be simple one-line code using the last ARX PR). 

Probably we should add this info to the readme as well. 
  
 
> The files in the help are also used directly as parts of the website. For example, this page
> https://arx.deidentifier.org/overview/privacy-criteria/
> Simply contains the content of
> help/v3.9.1/methods/privacy.html
>If you add numbers (like 1.1. in this case) those would appear on the website...

I see. I didn't know about this. I will remove them and add them as comments. So at least when a file is opened one can be sure he is in the correct section and page by validating the file index and the image indices to avoid mistakes.  

> Not if you carefully took the screenshots in the first place.

I don't know how! I think the screenshot size may change depending on the screen size and resolution. 

> Currently, I'm not convinced that there are significant improvements, but I see a lot of changes. Might not make sense to change a lot for minor improvements. Why is GitHub better suited than our own webspace?

Because it can be used directly without waiting for a copy to be available in the ARX webspace. Another option is to automate the copy via Github actions e.g. after each commit. 

> But why? I don't see why we would benefit from tags and if we stick with the current layout, we can also easily update old versions of the help while keeping track of changes. I must admin, though, that this is a quite hypothetical scenario.

Because: (1) it is not what developers expected. (2) it is difficult to check a file history. Maybe we should add info to the readme files to explain that?

**Comment by prasser** [comment]
> (2) a simple way to test the uploaded files e.g. how they look in the browser.

This seems to be the major reason for most of the changes. But this is usually not needed. If you edit the files in an IDE like Eclipse, you can directly see the effect of the changes using the integrated browser. No need to upload the files to the ARX webspace or use GitHub pages AFAIK.

**Comment by idhamari** [comment]
Thanks for the info. It seems the help browser does not support image aspect ratio. Could you please explain the idea behind the used width and height? 
I will try to make the updated images have a similar size with similar or better visibility.  I am still not sure how much this will affect ARX website as it uses some content from Github as you mentioned.

**Comment by prasser** [comment]
What do you mean by "browser does not support image aspect ratio"? The idea of width and height is (I believe) that the size of the image can be controlled.

**Comment by idhamari** [comment]
> I meant using either width or height properties and the browser adapts the other property automatically and keeps the aspect ratio of the image (so no stretching happens). Yes, I  can control the exact size but I will have to calculate the correct size for each image so the image is not stretched.   

The code is here:

https://github.com/prasser/swtbrowser/blob/master/src/main/de/linearbits/swt/simplebrowser/tags/impl/HTML_IMG.java

Could be easy to add.

**Comment by prasser** [comment]
General comment: this PR mixes up too many things (reorganizations, index addition, fixing or extending description, replacing images). I suggest to break it up into smaller PRs, to increase the chance of something getting merged. Start with the most important changes first: fixing or extending descriptions (no changes to images) and ideally, one PR per section of the doc, so that they can be discussed independently (and discussions will be needed).

**Comment by idhamari** [comment]
Thanks for the feedback. Sure, I will break it into multiple PRs. I thought having multiple commits is the same!

**Comment by idhamari** [comment]
This PR will be replaced by simpler PRs

**Pull request closed without merging**
